services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  rag-app:
    build: .
    container_name: rag-support-agent
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      QDRANT_HOST: localhost
      QDRANT_PORT: 6333
      ENVIRONMENT: production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  qdrant_storage: